spring:
  application:
    name: microservice-gateway-zuul
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
server:
  port: 8040
  tomcat:
    uri-encoding: utf-8
    max-threads: 128 # 最大worker线程
    min-spare-threads: 64 # 最小worker线程
  undertow:
    io-threads: 8 # IO线程数，默认为CPU核心数，最小为2
    worker-threads: 40 # 阻塞任务线程池，值设置取决于系统的负载，默认为io-threads * 8
    buffer-size: 512 # 每块buffer的空间大小
    direct-buffers: true # 是否分配的直接内存
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

zuul:
  routes:
    eureka:
      path: /eureka/**
      serviceId: microservice-discovery-eureka
    user:
      path: /user-path/**
      serviceId: microservice-provider-user
    admin:
      path: /admin/**
      serviceId: microservice-admin
    consumer:
      paht: /movie/**
      serviceId: microservice-consumer-movie
  ignored-services: env,metrics,trace,dump,jolokia,info,configprops,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream
  ignored-patterns: /**/js/**,/**/css/**

security:
  name: admin
  password: password
  role: ADMIN.USER
  url: /user-path/simple/**./admin/**./eureka/**



#    security:
#       path: /**
#       sensitiveHeaders:
#       serviceId: microservice-security-oauth2

#
#security:
#  basic:
#    enabled: true   #启用SpringSecurity的安全配置项
#    path: /**
#  user:
#    name: admin    #认证用户名
#    password: 111111 #认证密码
#    role: user
#  sessions: never
#zuul:
#  routes:
#    microservice-provider-user2: /user/**


#zuul:
#  routes:
#    users:
#      path: /user-path/**
#      serviceId: microservice-provider-user2
#
#ribbon:
#  eureka:
#    enabled: false
#
#microservice-provider-user2:  #serviceId
#  ribbon:
#    listOfServers: http://192.168.60.166:7901,http://192.168.60.166:7900

#zuul:
#  routes:
#    user:
#      path: /user-path/**
#      url: http://192.168.60.166:7901







#      defaultZone: http://user:password123@localhost:8761/eureka
#security:
#  basic:
#    enabled: true    #启用SpringSecurity的安全配置项
#  user:
#    name: jmxjava    #认证用户名
#    password: jmxhello #认证密码
#    role: user