
---
server:
  port: 8761
spring:
  profiles: eureka1
eureka:
  instance:
    hostname: eureka1
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/
---
server:
  port: 8762
spring:
  profiles: eureka2
eureka:
  instance:
    hostname: eureka2
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/



#spring:
#  profiles: eureka1
#server:
#  port: 8761
#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: ${spring.cloud.client.ipAddress}
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      default-zone: http://192.168.62.232:8762/eureka
#    healthcheck:
#      enabled: true
#
#---
#spring:
#  profiles: eureka2
#server:
#  port: 8762
#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: ${spring.cloud.client.ipAddress}
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      default-zone: http://192.168.62.232:8761/eureka
#    healthcheck:
#          enabled: true