server:
  port: 8761
eureka:
  client:
    register-with-eureka: true #是否将eureka自身作为应用注册到eureka注册中心
    fetch-registry: false #为true时，可以启动，但报异常：Cannot execute request on any known server
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}