server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka1
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://eureka2:8762/eureka
    healthcheck:
      enabled: true