spring:
  application:
    name: microservice-discovery-eureka
  profiles:
    active: eureka2
  cloud:
    config:
      name: ${spring.application.name}
      profile: config,${spring.profiles.active}
#---
#server:
#  port: 8761
#spring:
#  profiles: eureka1
#eureka:
#  instance:
#    hostname: eureka1
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://eureka2:8762/eureka/
#---
#server:
#  port: 8762
#spring:
#  profiles: eureka2
#eureka:
#  instance:
#    hostname: eureka2
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://eureka1:8761/eureka/
#security:
#  basic:
#    enable: true
#  user:
#    name: user
#    password: password123
#
#spring:
#  application:
#    name:  microservice-discovery-eureka
#  profiles:
#    active: dev
#  cloud:
#    config:
#    # application name git
#      name: ${spring.application.name}
#    # profile name${config.profile:dev}
#      profile: ${spring.profiles.active:test},config2
#security:
#  basic:
#    enabled: true    #启用SpringSecurity的安全配置项
#  user:
#    name: jmxjava    #认证用户名
#    password: jmxhello #认证密码
#    role: user