server:
  port: 8764
spring:
  application:
    name: microservice-security-oauth2    # 服务名称
  jpa:
      generate-ddl: false
      show-sql: true
      hibernate:
        ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  redis:
    host: 192.168.10.105
    port: 6379
    password:
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.itmuch: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

security:
    oauth2:
      resource:
        filter-order: 3